sms_settings:
 username: "ACc967eebc9c8a2ab9e9c992a396f866e6"
 password: "2da4feef75471cf92d081e8d46851fac"
 sendername: "+12564856086"
 host_url: "https://api.twilio.com/2010-04-01/Accounts/ACc967eebc9c8a2ab9e9c992a396f866e6/Messages.json"
 success_code: "success"

parameter_mappings:
 username: username
 password: password
 sendername: From
 message: Body
 phone: To

# Additional parameters to be added should given in the format "param1=value1&param2=value2&..."
additional_parameters: ""
 