sms_settings:
 username: "itsourceltd"
 password: "2AigkYJH"
 sendername: "ChotroSchool"
 host_url: "http://api.bulksms.icombd.com/restapi/sms/1/text/single/"
 success_code: "PENDING"

parameter_mappings:
 username: username
 password: password
 sendername: from
 message: text
 phone: to

# Additional parameters to be added should given in the format "param1=value1&param2=value2&..."
additional_parameters: ""
 